# -  /SuhailTechInfo/

FROM quay.io/suhailtechinfo/suhail-v2
RUN git clone https://github.com/12qfm9/tech /root/12qfm9
WORKDIR /root/12qfm9/
RUN npm install
EXPOSE 8000
CMD ["npm","start" ] 
  
# -  /SuhailTechInfo/ Don't change this name,



